name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ' '

      - name: Deploy
        run: bash ./_deploy/init.sh
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          DOMAIN: ${{ secrets.DOMAIN }}
          ENV_FILE: ${{ secrets.ENV_FILE || ' ' }}
